version: '3'
services:
  pig-mysql:
    container_name: pig-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    image: fjwangzy/pig-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  pig-redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    restart: always
    container_name: pig-redis
    hostname: pig-redis

  pig-register:
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    container_name: pig-register
    hostname: pig-register
    image: fjwangzy/pig-register
    depends_on:
      - pig-mysql
      - pig-redis

  pig-gateway:
    ports:
      - 9999:9999
    container_name: pig-gateway
    hostname: pig-gateway
    image: fjwangzy/pig-gateway
    depends_on:
      - pig-register

  pig-auth:
    restart: always
    container_name: pig-auth
    hostname: pig-auth
    image: fjwangzy/pig-auth
    depends_on:
      - pig-gateway

  pig-upms:
    restart: always
    container_name: pig-upms
    hostname: pig-upms
    image: fjwangzy/pig-upms
    depends_on:
      - pig-gateway

  # pig-monitor:
  #   restart: always
  #   ports:
  #     - 5001:5001
  #   container_name: pig-monitor
  #   hostname: pig-monitor
  #   image: fjwangzy/pig-monitor
  #   depends_on:
  #     - pig-gateway

  # pig-sentinel:
  #   build:
  #     context: ./pig-visual/pig-sentinel-dashboard
  #   restart: always
  #   image: fjwangzy/pig-sentinel
  #   container_name: pig-sentinel
  #   ports:
  #     - 5003:5003

  pig-codegen:
    build:
      context: ./pig-visual/pig-codegen
    restart: always
    container_name: pig-codegen
    hostname: pig-codegen
    image: fjwangzy/pig-codegen
    depends_on:
      - pig-gateway

  pig-job:
    restart: always
    container_name: pig-job
    hostname: pig-job
    image: fjwangzy/pig-job
    ports:
      - 5004:5004
    depends_on:
    - pig-gateway
